### ISSUE TITLE
Functional Component formatting

### ISSUE THREAD

**Issue by vladinator1000** [jeantimex/react-sublime-snippet#1]
Hi there, great job on this, I'm really digging it!

I was wondering if there's a way to customise the functional component in this format, rather than multiple lines? It's just a personal preference of mine.

```
const Component = ({ className, }) => {
    return (

    );
};

```

**Comment by jeantimex** [comment]
@Sounds good @savovs! If there's just one prop, then make it one-liner seems cleaner. Thanks for your suggestion, I will put this to the next release.

**Comment by vladinator1000** [comment]
Awesome, it's not a deal breaker, but for some reason it breaks the colour codingin sublime as well. ![](http://i.imgur.com/rRXz33h.png)

**Comment by jeantimex** [comment]
In terms of the color issue, it might be to do with the syntax package. I've committed the change to make the prop one-liner. Going to add some more useful snippets, will make a new release soon. Thanks for your support mate!

**Comment by jeantimex** [comment]
v3.0.2 is released, it includes the change to make the functional component cleaner. :)
